/**
 * Runs SpaceInvaders. Some of the content in this file was generated by/edited with AI tools.
 * This citation is to abide by the syllabus requirement that "appropriate citations"
 * must be given when referring to external sources. More information is available upon request.
 */

#include <SDL3/SDL.h>
#include <iostream>
#include "../engine/headers/input.h"
#include "../engine/headers/EventManager.h"
#include "../engine/headers/render.h"
#include "SpaceInvaders/SpaceInvadersGame.h" // Adjust path if needed
#include "BubbleShooter/BubbleShooter.h"

int main(int argc, char* argv[]) {
    // 1. Initialize SDL and Window (Using your render.cpp helpers)
    initializeSDL();
    
    SDL_Window* window = nullptr;
    SDL_Renderer* renderer = nullptr;
    createWindowAndRenderer(&window, &renderer);

    if (!window || !renderer) {
        std::cerr << "Failed to initialize Window/Renderer" << std::endl;
        return -1;
    }

    // 2. Initialize Engine Systems
    EventManager eventMgr;
    InputManager input(eventMgr);

    // 3. Initialize The Game
    BubbleShooter game(renderer, &input);
    game.Init();

    // 4. The Main Loop
    bool isRunning = true;
    Uint64 lastTime = SDL_GetTicks();

    while (isRunning && !game.IsGameOver()) {
        // A. Calculate Delta Time
        Uint64 currentTime = SDL_GetTicks();
        float dt = (currentTime - lastTime) / 1000.0f;
        lastTime = currentTime;

        // B. Input Polling (SDL Events)
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_EVENT_QUIT) {
                isRunning = false;
            }
        }

        // C. Update Systems
        // NOTE: Call game.Update BEFORE input.update so that
        // `InputManager::isPressed` sees the transition from the
        // previous frame and returns true on the frame the key
        // was pressed. InputManager::update() saves the current
        // keyboard state into the previous-state buffer, which
        // would otherwise make isPressed always false if called
        // before the game's Update.
        game.Update(dt);
        input.update(); // Update key states and check chords

        // Process queued events (e.g., chords -> InputEvent). Use steady_clock
        // so timestamps generated by InputManager/InputEvent match the processing time.
        eventMgr.ProcessEvents(std::chrono::steady_clock::now().time_since_epoch().count());

        // D. Render
        SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255); // Clear to Black
        SDL_RenderClear(renderer);
        
        game.Render();

        SDL_RenderPresent(renderer);
        
        // Simple frame cap (optional)
        SDL_Delay(16); 
    }

    // 5. Cleanup
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();

    return 0;
}