/**
 * Header file for declarations of functions for SpaceInvaders. Some of the content in this file was generated by/edited with AI tools.
 * This citation is to abide by the syllabus requirement that "appropriate citations"
 * must be given when referring to external sources. More information is available upon request.
 */

#pragma once

#include <vector>
#include <string>
#include <SDL3/SDL.h>
#include "../../engine/headers/GameObject.h"
#include "../../engine/headers/GameObjectPool.h"
#include "../../engine/headers/input.h"
#include "../../engine/headers/render.h"
#include "../../engine/headers/collisions.h"

// Game Constants
const int BULLET_POOL_SIZE = 50;
const int ALIEN_ROWS = 5;
const int ALIEN_COLS = 11;

// Action IDs for Input Manager
const int ACTION_LEFT = 1;
const int ACTION_RIGHT = 2;
const int ACTION_SHOOT = 3;
const int ACTION_NUKE = 4; // The Chord Action

class SpaceInvaders
{
public:
    SpaceInvaders(SDL_Renderer *renderer, InputManager *input, EventManager *eventMgr);
    ~SpaceInvaders();

    void Init();
    void Update(float dt);
    void Render();
    bool IsGameOver() const { return gameOver; }

private:
    // Engine Systems
    SDL_Renderer *m_renderer;
    InputManager *m_input;
    EventManager *m_eventMgr;

    // Entities
    GameObject *m_player;
    std::vector<GameObject *> m_aliens;

    GameObjectPool *m_bulletPool;
    std::vector<GameObject *> m_activeBullets;

    // Game State
    bool gameOver;
    float alienMoveTimer;
    float alienMoveInterval;
    int alienDirection; // 1 = right, -1 = left
    bool alienDropdown; // true if they need to drop down this frame

    // Helpers
    void SpawnAliens();
    void FireBullet();
    void TriggerNuke();
    void HandleCollisions();

    // Basic Texture creation (placeholders)
    SDL_Texture *CreateColoredTexture(int w, int h, int r, int g, int b);
    SDL_Texture *m_texPlayer;
    SDL_Texture *m_texAlien;
    SDL_Texture *m_texBullet;
};