/**
 * This file outlines the necessary functions to run game 1, SpaceInvaders. Some of the content in this file was generated by/edited with AI tools.
 * This citation is to abide by the syllabus requirement that "appropriate citations"
 * must be given when referring to external sources. More information is available upon request.
 */

#include "SpaceInvadersGame.h"
#include <iostream>
#include "../../engine/headers/EventManager.h"

SpaceInvaders::SpaceInvaders(SDL_Renderer* renderer, InputManager* input, EventManager* eventMgr)
    : m_renderer(renderer), m_input(input), m_eventMgr(eventMgr), 
      gameOver(false), alienMoveTimer(0), alienMoveInterval(.1f), alienDirection(1), alienDropdown(false)
{
    // Initialize the pool
    // Assuming sizeof(GameObject) is the slot size
    m_bulletPool = new GameObjectPool(sizeof(GameObject), BULLET_POOL_SIZE);
}

SpaceInvaders::~SpaceInvaders() {
    delete m_bulletPool;
    delete m_player;
    for (auto a : m_aliens) delete a;
    // activeBullets are owned by the pool, so we don't delete them directly here
    // but we should technically return them to the pool if we were being strict.
}

SDL_Texture* SpaceInvaders::CreateColoredTexture(int w, int h, int r, int g, int b) {
    SDL_Surface* surf = SDL_CreateSurface(w, h, SDL_PIXELFORMAT_RGBA8888);
    SDL_FillSurfaceRect(surf, NULL, SDL_MapRGB(SDL_GetPixelFormatDetails(surf->format), NULL, r, g, b));
    SDL_Texture* tex = SDL_CreateTextureFromSurface(m_renderer, surf);
    SDL_DestroySurface(surf);
    return tex;
}

void SpaceInvaders::Init() {
    // 1. Create Textures
    m_texPlayer = CreateColoredTexture(40, 20, 0, 255, 0);   // Green Player
    m_texAlien  = CreateColoredTexture(30, 20, 255, 255, 255); // White Alien
    m_texBullet = CreateColoredTexture(5, 15, 255, 0, 0);     // Red Bullet

    // 2. Setup Input Bindings
    m_input->bindKey(SDL_SCANCODE_LEFT, ACTION_LEFT, InputManager::InputType::Simple);
    m_input->bindKey(SDL_SCANCODE_RIGHT, ACTION_RIGHT, InputManager::InputType::Simple);
    m_input->bindKey(SDL_SCANCODE_SPACE, ACTION_SHOOT, InputManager::InputType::Simple);

    // SECTION 2: CHORD (Shift + Space = Nuke)
    // This allows you to clear the screen or shoot a massive beam
    std::vector<SDL_Scancode> nukeChord = { SDL_SCANCODE_LSHIFT, SDL_SCANCODE_SPACE };
    m_input->bindChord(nukeChord, ACTION_NUKE);

    // Register to listen for input events (so chord/key events can be handled)
    if (m_eventMgr) {
        m_eventMgr->RegisterListener(InputEvent::STATIC_EVENT_TYPE_ID,
            [this](const Event &e) {
                const InputEvent &ie = static_cast<const InputEvent&>(e);
                if (ie.action == ACTION_SHOOT) {
                    // Only fire if shift isn't down (guard in listener too)
                    if (!m_input->isDown(SDL_SCANCODE_LSHIFT)) FireBullet();
                } else if (ie.action == ACTION_NUKE) {
                    TriggerNuke();
                }
            }
        );
    }

    // 3. Create Player
    m_player = new GameObject();
    m_player->setComponent("position", Vector{400, 550});
    m_player->setComponent("dimensions", Vector{40, 20});
    // Assuming you have a way to set the texture in your component system
    // For now we'll handle rendering manually in Render() using the texture members

    // 4. Spawn Aliens
    SpawnAliens();
}

void SpaceInvaders::SpawnAliens() {
    float startX = 50;
    float startY = 50;
    float gapX = 50;
    float gapY = 40;

    for (int row = 0; row < ALIEN_ROWS; ++row) {
        for (int col = 0; col < ALIEN_COLS; ++col) {
            GameObject* alien = new GameObject();
            alien->setComponent("position", Vector{startX + (col * gapX), startY + (row * gapY)});
            alien->setComponent("dimensions", Vector{30, 20});
            alien->setComponent("active", true); // Custom component to track life
            // Tag the alien with its row so we can drop specific rows on edge hit
            alien->setComponent("alien_row", row);
            m_aliens.push_back(alien);
        }
    }
}

void SpaceInvaders::Update(float dt) {
    if (gameOver) return;

    // --- 1. Handle Input Events ---
    // Note: In your engine, events are queued. You likely need to poll the EventManager here.
    // For this example, I'll check the InputManager state directly if your engine permits, 
    // OR you process the event queue here. 
    // Assuming simple state checks for movement:
    
    Vector pPos = m_player->getComponent<Vector>("position");
    float speed = 200.0f * dt;

    if (m_input->isDown(SDL_SCANCODE_LEFT)) {
        pPos.x -= speed;
    }
    if (m_input->isDown(SDL_SCANCODE_RIGHT)) {
        pPos.x += speed;
    }
    // Clamp Player
    if (pPos.x < 20) pPos.x = 20;
    if (pPos.x > WINDOW_WIDTH - 20) pPos.x = WINDOW_WIDTH - 20;
    m_player->setComponent("position", pPos);

    // Handle Shooting (Check if event triggered this frame)
    // Note: You might need to pop events from your EventManager queue here.
    // pseudo-code:
    // while(event = m_eventMgr->poll()) {
    //    if (event->id == ACTION_SHOOT) FireBullet();
    //    if (event->id == ACTION_NUKE) TriggerNuke();
    // }
    // For simplicity, using isPressed:
    if (m_input->isPressed(SDL_SCANCODE_SPACE) && !m_input->isDown(SDL_SCANCODE_LSHIFT)) {
        FireBullet();
    }
    // Check Chord State (usually handled by event system, but we can verify)
    // If your EventManager emitted ACTION_NUKE, call TriggerNuke()

    // --- 2. Update Bullets ---
    for (int i = 0; i < m_activeBullets.size(); ++i) {
        GameObject* b = m_activeBullets[i];
        Vector bPos = b->getComponent<Vector>("position");
        bPos.y -= 400.0f * dt; // Bullet Speed
        b->setComponent("position", bPos);

        // Despawn if off screen
        if (bPos.y < 0) {
            // RETURN TO POOL
            m_bulletPool->despawn(b);
            m_activeBullets.erase(m_activeBullets.begin() + i);
            i--;
        }
    }

    // --- 3. Update Aliens ---
    alienMoveTimer += dt;
    if (alienMoveTimer >= alienMoveInterval) {
        alienMoveTimer = 0;

        // Track which rows need to drop this tick
        std::vector<bool> rowShouldDrop(ALIEN_ROWS, false);

        // First pass: move horizontally and detect per-row edge collisions
        for (auto alien : m_aliens) {
            if (!alien->getComponent<bool>("active")) continue;

            Vector pos = alien->getComponent<Vector>("position");
            pos.x += 10 * alienDirection;
            alien->setComponent("position", pos);

            // Check edges and mark the alien's row for dropping
            if (pos.x < 30 || pos.x > WINDOW_WIDTH - 30) {
                int row = alien->getComponent<int>("alien_row");
                if (row >= 0 && row < ALIEN_ROWS) rowShouldDrop[row] = true;
            }
        }

        // If any row needs to drop, reverse direction for the formation
        bool anyDrop = false;
        for (bool v : rowShouldDrop) if (v) { anyDrop = true; break; }

        if (anyDrop) {
            alienDirection *= -1;

            // Drop only the rows that hit the edge
            for (auto alien : m_aliens) {
                if (!alien->getComponent<bool>("active")) continue;
                int row = alien->getComponent<int>("alien_row");
                if (row >= 0 && row < ALIEN_ROWS && rowShouldDrop[row]) {
                    Vector pos = alien->getComponent<Vector>("position");
                    pos.y += 20; // Drop down one level for that row
                    alien->setComponent("position", pos);
                }
            }
        }
    }
    
    HandleCollisions();
}

void SpaceInvaders::FireBullet() {
    // SECTION 1: Use the Allocator Pool
    GameObject* bullet = m_bulletPool->spawn();
    
    if (bullet) {
        Vector pPos = m_player->getComponent<Vector>("position");
        // Initialize the bullet (it might have old data from previous use)
        bullet->setComponent("position", Vector{pPos.x, pPos.y - 20});
        bullet->setComponent("dimensions", Vector{5, 15});
        bullet->setComponent("active", true);
        
        m_activeBullets.push_back(bullet);
    } else {
        std::cout << "Bullet Pool Empty!" << std::endl;
    }
}

void SpaceInvaders::TriggerNuke() {
    // SECTION 2: Chord Behavior
    // Example: Kill all aliens in the bottom row
    std::cout << "NUKE TRIGGERED!" << std::endl;
    for (auto alien : m_aliens) {
         if (alien->getComponent<bool>("active")) {
             alien->setComponent("active", false); // Just kill everyone for fun/demo
         }
    }
}

void SpaceInvaders::HandleCollisions() {
    // Brute force collision O(N*M) - fine for Space Invaders
    for (int i = 0; i < m_activeBullets.size(); ++i) {
        GameObject* b = m_activeBullets[i];
        bool bulletHit = false;

        for (auto alien : m_aliens) {
            if (!alien->getComponent<bool>("active")) continue;

            // Use your engine's collision check
            if (overlappingColliders1(*b, *alien)) {
                alien->setComponent("active", false); // Kill Alien
                bulletHit = true;
                break; // Bullet can only hit one alien
            }
        }

        if (bulletHit) {
            // Return bullet to pool
            m_bulletPool->despawn(b);
            m_activeBullets.erase(m_activeBullets.begin() + i);
            i--;
        }
    }
}

void SpaceInvaders::Render() {
    // Render Player
    RenderComponent rcPlayer(m_texPlayer);
    rcPlayer.render(m_renderer, m_player->getComponent<Vector>("position"), m_player->getComponent<Vector>("dimensions"));

    // Render Aliens
    RenderComponent rcAlien(m_texAlien);
    for (auto alien : m_aliens) {
        if (alien->getComponent<bool>("active")) {
            rcAlien.render(m_renderer, alien->getComponent<Vector>("position"), alien->getComponent<Vector>("dimensions"));
        }
    }

    // Render Bullets
    RenderComponent rcBullet(m_texBullet);
    for (auto b : m_activeBullets) {
        rcBullet.render(m_renderer, b->getComponent<Vector>("position"), b->getComponent<Vector>("dimensions"));
    }
}