/**
 * This file outlines the function definitions for EventManager.h. Some of the content in this file was generated by/edited with AI tools.
 * This citation is to abide by the syllabus requirement that "appropriate citations"
 * must be given when referring to external sources. More information is available upon request.
 */

#include "../headers/EventManager.h"
#include "../headers/timeline.h"
#include "../headers/Event.h"

const EventTypeID CollisionEvent::STATIC_EVENT_TYPE_ID = ::GetEventTypeID("CollisionEvent");
const EventTypeID InputEvent::STATIC_EVENT_TYPE_ID = ::GetEventTypeID("InputEvent");
const EventTypeID DeathEvent::STATIC_EVENT_TYPE_ID = ::GetEventTypeID("DeathEvent");
const EventTypeID SpawnEvent::STATIC_EVENT_TYPE_ID = ::GetEventTypeID("SpawnEvent");

void EventManager::ProcessEvents(float currentTimestamp)
{

    std::vector<std::shared_ptr<Event>> readyEvents;

    // Keep processing events as long as the queue is not empty
    // and the top event's timestamp is at or before the current time
    while (!eventQueue.empty() && eventQueue.top()->timestamp <= currentTimestamp)
    {
        readyEvents.push_back(eventQueue.top());
        eventQueue.pop();
    }

    for (const auto& event : readyEvents) {

        // We call the virtual function GetEventTypeID()
        // instead of accessing a 'type' member.
        EventTypeID type = event->GetEventTypeID();

        if (listeners.find(type) != listeners.end()) {
            // Call each listener's callback function
            for (const auto& callback : listeners.at(type)) {
                callback(*event); // Pass the event to the listener
            }
        }
    }
}

void EventManager::QueueEvent(std::shared_ptr<Event> event)
{
    eventQueue.push(event);
}

void EventManager::RegisterListener(EventTypeID type, ListenerCallback callback)
{
    listeners[type].push_back(callback);
}
