/**
 * This file outlines the function definitions for EventManager.h. Some of the content in this file was generated by/edited with AI tools.
 * This citation is to abide by the syllabus requirement that "appropriate citations"
 * must be given when referring to external sources. More information is available upon request.
 */

#include "../headers/EventManager.h"
#include "../headers/timeline.h"
#include "../headers/Event.h"

void EventManager::ProcessEvents(float currentTimestamp) {
    // Keep processing events as long as the queue is not empty
    // AND the top event's timestamp is at or before the current time
    while (!eventQueue.empty() && eventQueue.top()->timestamp <= currentTimestamp) {

        // 1. Get the event from the queue
        std::shared_ptr<Event> event = eventQueue.top();
        eventQueue.pop();

        // 2. Find all listeners for this event type
        EventType type = event->type;
        if (listeners.find(type) != listeners.end()) {

            // 3. Call each listener's callback function
            for (const auto& callback : listeners.at(type)) {
                callback(*event); // Pass the event to the listener
            }
        }
    }
}

void EventManager::QueueEvent(std::shared_ptr<Event> event) {
    eventQueue.push(event);
}

void EventManager::RegisterListener(EventType type, ListenerCallback callback) {
    listeners[type].push_back(callback);
}
