/**
 * This file outlines the necessary functions to run game 2, BubbleShooter. Some of the content in this file was generated by/edited with AI tools.
 * This citation is to abide by the syllabus requirement that "appropriate citations"
 * must be given when referring to external sources. More information is available upon request.
 */

#include "BubbleShooter.h"
#include <iostream>
#include <cstdlib>
#include <set>       // Needed for the cluster finding logic
#include <algorithm> // Needed for finding elements in vector

// how many shots before the roof drops?
const int SHOTS_PER_DROP = 6; 

BubbleShooter::BubbleShooter(SDL_Renderer* renderer, InputManager* input)
    : m_renderer(renderer), m_input(input), m_shooterAngle(0.0f), m_projectile(nullptr), gameOver(false)
{
    // Initialize Pool
    m_bubblePool = new GameObjectPool(sizeof(GameObject), SHOOTER_POOL_SIZE);
    
    // Shooter is at bottom center
    m_shooterPos = Vector{400, 550}; 
    
    // Clear grid
    for(int r=0; r<GRID_ROWS; r++)
        for(int c=0; c<GRID_COLS; c++)
            m_grid[r][c] = nullptr;
            
    // Seed random for colors
    std::srand(SDL_GetTicks());
}

BubbleShooter::~BubbleShooter() {
    delete m_bubblePool;
    if (m_texRed) SDL_DestroyTexture(m_texRed);
    if (m_texBlue) SDL_DestroyTexture(m_texBlue);
    if (m_texGreen) SDL_DestroyTexture(m_texGreen);
}

SDL_Texture* BubbleShooter::CreateColoredTexture(int r, int g, int b) {
    SDL_Surface* surf = SDL_CreateSurface(BUBBLE_RADIUS*2, BUBBLE_RADIUS*2, SDL_PIXELFORMAT_RGBA8888);
    SDL_FillSurfaceRect(surf, NULL, SDL_MapRGB(SDL_GetPixelFormatDetails(surf->format), NULL, r, g, b));
    SDL_Texture* tex = SDL_CreateTextureFromSurface(m_renderer, surf);
    SDL_DestroySurface(surf);
    return tex;
}

Vector BubbleShooter::GridToPixel(int row, int col) {
    float x = col * (BUBBLE_RADIUS * 2);
    float y = row * (BUBBLE_RADIUS * 1.732f); 

    // Offset odd rows
    if (row % 2 != 0) {
        x += BUBBLE_RADIUS;
    }

    x += 50; 
    y += 50;
    return Vector{x, y};
}

void BubbleShooter::Init() {
    m_texRed   = CreateColoredTexture(255, 50, 50);   
    m_texBlue  = CreateColoredTexture(50, 50, 255);   
    m_texGreen = CreateColoredTexture(50, 255, 50);   

    // Fill top 3 rows
    for(int r=0; r<3; r++) {
        for(int c=0; c<GRID_COLS; c++) {
            if(r%2 != 0 && c == GRID_COLS-1) continue;

            GameObject* b = m_bubblePool->spawn();
            b->setComponent("position", GridToPixel(r, c));
            b->setComponent("dimensions", Vector{BUBBLE_RADIUS*2, BUBBLE_RADIUS*2});
            
            int colorId = std::rand() % 3; 
            b->setComponent("color", colorId);
            
            m_grid[r][c] = b;
        }
    }

    SpawnNextBubble();

    m_input->bindKey(SDL_SCANCODE_LEFT, BS_ACTION_LEFT, InputManager::InputType::Simple);
    m_input->bindKey(SDL_SCANCODE_RIGHT, BS_ACTION_RIGHT, InputManager::InputType::Simple);
    m_input->bindKey(SDL_SCANCODE_SPACE, BS_ACTION_FIRE, InputManager::InputType::Simple);
}

void BubbleShooter::SpawnNextBubble() {
    m_currentBubble = m_bubblePool->spawn();
    m_currentBubble->setComponent("position", m_shooterPos);
    m_currentBubble->setComponent("dimensions", Vector{BUBBLE_RADIUS*2, BUBBLE_RADIUS*2});
    
    int colorId = std::rand() % 3; 
    m_currentBubble->setComponent("color", colorId);
}

void BubbleShooter::Update(float dt) {
    if (gameOver) return;

    if (m_input->isDown(SDL_SCANCODE_LEFT)) m_shooterAngle -= 100 * dt;
    if (m_input->isDown(SDL_SCANCODE_RIGHT)) m_shooterAngle += 100 * dt;
    if (m_shooterAngle < -80) m_shooterAngle = -80;
    if (m_shooterAngle > 80) m_shooterAngle = 80;

    if (m_input->isPressed(SDL_SCANCODE_SPACE) && m_projectile == nullptr) {
        Fire();
    }

    if (m_projectile) {
        Vector pos = m_projectile->getComponent<Vector>("position");
        pos.x += m_projectileVelocity.x * dt;
        pos.y += m_projectileVelocity.y * dt;
        m_projectile->setComponent("position", pos);

        // Wall Bounce
        if (pos.x < BUBBLE_RADIUS || pos.x > 800 - BUBBLE_RADIUS) {
            m_projectileVelocity.x *= -1;
            if (pos.x < BUBBLE_RADIUS) pos.x = BUBBLE_RADIUS + 1;
            else pos.x = 800 - BUBBLE_RADIUS - 1;
        }

        // Ceiling Hit
        if (pos.y < BUBBLE_RADIUS) {
            SnapToGrid(m_projectile);
            m_projectile = nullptr;
            SpawnNextBubble();
            return;
        }

        // Collision
        for(int r=0; r<GRID_ROWS; r++) {
            for(int c=0; c<GRID_COLS; c++) {
                GameObject* other = m_grid[r][c];
                if (other && CheckCircleCollision(m_projectile, other)) {
                    SnapToGrid(m_projectile);
                    m_projectile = nullptr;
                    SpawnNextBubble();
                    return; 
                }
            }
        }
    }
}

void BubbleShooter::Fire() {
    m_projectile = m_currentBubble;
    m_currentBubble = nullptr; 

    float rad = (m_shooterAngle - 90) * (3.14159f / 180.0f);
    float speed = 600.0f;
    m_projectileVelocity = Vector{ std::cos(rad) * speed, std::sin(rad) * speed };
    
    static int shotsFired = 0;
    shotsFired++;
    
    if (shotsFired >= SHOTS_PER_DROP) {
        DropGrid();
        shotsFired = 0;
    }
}

void BubbleShooter::DropGrid() {
    for(int c=0; c<GRID_COLS; c++) {
        if (m_grid[GRID_ROWS-1][c] != nullptr) {
            gameOver = true;
            std::cout << "GAME OVER: Bubbles hit the bottom!" << std::endl;
        }
    }

    for(int r = GRID_ROWS - 2; r >= 0; r--) {
        for(int c = 0; c < GRID_COLS; c++) {
            m_grid[r+1][c] = m_grid[r][c]; 
            m_grid[r][c] = nullptr;        
            
            if (m_grid[r+1][c]) {
                m_grid[r+1][c]->setComponent("position", GridToPixel(r+1, c));
            }
        }
    }
}

bool BubbleShooter::CheckCircleCollision(GameObject* a, GameObject* b) {
    Vector p1 = a->getComponent<Vector>("position");
    Vector p2 = b->getComponent<Vector>("position");
    float dx = p1.x - p2.x;
    float dy = p1.y - p2.y;
    float distSq = dx*dx + dy*dy;
    float radiusSum = BUBBLE_RADIUS * 2;
    return distSq < (radiusSum * radiusSum * 0.8f); 
}

void BubbleShooter::SnapToGrid(GameObject* bubble) {
    Vector bPos = bubble->getComponent<Vector>("position");
    int bestR = -1, bestC = -1;
    float minDist = 100000.0f;

    for(int r=0; r<GRID_ROWS; r++) {
        for(int c=0; c<GRID_COLS; c++) {
            if (m_grid[r][c] == nullptr) {
                Vector slotPos = GridToPixel(r, c);
                float dx = bPos.x - slotPos.x;
                float dy = bPos.y - slotPos.y;
                float dist = dx*dx + dy*dy;
                
                if (dist < minDist) {
                    minDist = dist;
                    bestR = r;
                    bestC = c;
                }
            }
        }
    }

    if (bestR != -1) {
        m_grid[bestR][bestC] = bubble;
        bubble->setComponent("position", GridToPixel(bestR, bestC));
        
        // --- NEW: MATCH 3 LOGIC ---
        // 1. Find all matching neighbors
        std::set<std::pair<int, int>> matches;
        int targetColor = bubble->getComponent<int>("color");
        FindCluster(bestR, bestC, targetColor, matches);

        // 2. If 3 or more, remove them
        if (matches.size() >= 3) {
            for (auto const& [r, c] : matches) {
                // Despawn object back to pool
                m_bubblePool->despawn(m_grid[r][c]);
                // Clear grid slot
                m_grid[r][c] = nullptr;
            }
            std::cout << "Popped " << matches.size() << " bubbles!" << std::endl;
        }
        // --------------------------

        if (bestR == GRID_ROWS - 1) {
            gameOver = true;
            std::cout << "GAME OVER: Bubbles reached bottom!" << std::endl;
        }
    } else {
        m_bubblePool->despawn(bubble);
    }
}

void BubbleShooter::DrawTrajectory() {
    // 1. Setup Simulation Variables
    // Start at shooter position (centered)
    float simX = m_shooterPos.x;
    float simY = m_shooterPos.y;
    
    // Calculate direction vector based on current angle
    float rad = (m_shooterAngle - 90) * (3.14159f / 180.0f);
    float dirX = std::cos(rad);
    float dirY = std::sin(rad);

    // Set line color (White)
    SDL_SetRenderDrawColor(m_renderer, 255, 255, 255, 255);

    // 2. Simulation Loop
    // We step forward 10 pixels at a time to check for collisions
    // We limit the loop to 150 steps so we don't draw infinite lines
    for (int i = 0; i < 150; i++) {
        
        // Move the simulation point forward
        float stepSize = 10.0f;
        float nextX = simX + dirX * stepSize;
        float nextY = simY + dirY * stepSize;

        // --- A. CHECK WALL BOUNCE ---
        if (nextX < BUBBLE_RADIUS || nextX > 800 - BUBBLE_RADIUS) {
            dirX *= -1; // Reflect horizontal direction
            // Clamp to wall
            if (nextX < BUBBLE_RADIUS) nextX = BUBBLE_RADIUS + 1;
            else nextX = 800 - BUBBLE_RADIUS - 1;
        }

        // --- B. CHECK CEILING ---
        if (nextY < BUBBLE_RADIUS) {
            break; // Stop drawing
        }

        // --- C. CHECK BUBBLE COLLISION ---
        bool hit = false;
        // We do a simplified check against the grid
        for(int r=0; r<GRID_ROWS; r++) {
            for(int c=0; c<GRID_COLS; c++) {
                GameObject* b = m_grid[r][c];
                if(b) {
                    Vector bPos = b->getComponent<Vector>("position");
                    float dx = nextX - bPos.x;
                    float dy = nextY - bPos.y;
                    // Check squared distance against radius + buffer
                    if ((dx*dx + dy*dy) < (BUBBLE_RADIUS * 2 * BUBBLE_RADIUS * 2)) {
                        hit = true;
                        break;
                    }
                }
            }
            if(hit) break;
        }

        if (hit) break; // Stop drawing line

        // --- D. DRAW SEGMENT ---
        // Draw a small dot or line segment
        SDL_RenderLine(m_renderer, (int)simX, (int)simY, (int)nextX, (int)nextY);

        // Update current sim position
        simX = nextX;
        simY = nextY;
    }
}

// --- NEW HELPER: Recursive Flood Fill ---
void BubbleShooter::FindCluster(int r, int c, int targetColor, std::set<std::pair<int, int>>& visited) {
    // 1. Boundary Checks
    if (r < 0 || r >= GRID_ROWS || c < 0 || c >= GRID_COLS) return;
    if (m_grid[r][c] == nullptr) return;
    
    // 2. Check Color
    if (m_grid[r][c]->getComponent<int>("color") != targetColor) return;

    // 3. Check if already visited
    if (visited.count({r, c})) return;

    // 4. Add to visited set
    visited.insert({r, c});

    // 5. Check Neighbors (Hex Grid Offsets)
    // Even Row Neighbors: (r-1, c-1), (r-1, c), (r, c-1), (r, c+1), (r+1, c-1), (r+1, c)
    // Odd Row Neighbors:  (r-1, c), (r-1, c+1), (r, c-1), (r, c+1), (r+1, c), (r+1, c+1)
    
    int offsetsEven[6][2] = {{-1, -1}, {-1, 0}, {0, -1}, {0, 1}, {1, -1}, {1, 0}};
    int offsetsOdd[6][2]  = {{-1, 0}, {-1, 1}, {0, -1}, {0, 1}, {1, 0}, {1, 1}};

    auto& offsets = (r % 2 == 0) ? offsetsEven : offsetsOdd;

    for (int i = 0; i < 6; ++i) {
        FindCluster(r + offsets[i][0], c + offsets[i][1], targetColor, visited);
    }
}

void BubbleShooter::Render() {
    if (!gameOver) {
        DrawTrajectory();
    }
    
    for(int r=0; r<GRID_ROWS; r++) {
        for(int c=0; c<GRID_COLS; c++) {
            GameObject* b = m_grid[r][c];
            if(b) {
                int color = b->getComponent<int>("color");
                SDL_Texture* texToDraw = m_texGreen; 
                if(color == 0) texToDraw = m_texRed;
                if(color == 1) texToDraw = m_texBlue;
                
                RenderComponent rc(texToDraw);
                rc.render(m_renderer, b->getComponent<Vector>("position"), b->getComponent<Vector>("dimensions"));
            }
        }
    }

    if (m_currentBubble) {
        int color = m_currentBubble->getComponent<int>("color");
        SDL_Texture* texToDraw = m_texGreen;
        if(color == 0) texToDraw = m_texRed;
        if(color == 1) texToDraw = m_texBlue;

        RenderComponent rc(texToDraw);
        rc.render(m_renderer, m_currentBubble->getComponent<Vector>("position"), m_currentBubble->getComponent<Vector>("dimensions"));
    }

    if(m_projectile) {
        int color = m_projectile->getComponent<int>("color");
        SDL_Texture* texToDraw = m_texGreen;
        if(color == 0) texToDraw = m_texRed;
        if(color == 1) texToDraw = m_texBlue;

        RenderComponent rc(texToDraw);
        rc.render(m_renderer, m_projectile->getComponent<Vector>("position"), m_projectile->getComponent<Vector>("dimensions"));
    }
}