/**
 * Header file for declarations of functions for BubbleShooter. Some of the content in this file was generated by/edited with AI tools.
 * This citation is to abide by the syllabus requirement that "appropriate citations"
 * must be given when referring to external sources. More information is available upon request.
 */

#pragma once

#include <vector>
#include <cmath>
#include <set>
#include "../../engine/headers/GameObject.h"
#include "../../engine/headers/GameObjectPool.h"
#include "../../engine/headers/input.h"
#include "../../engine/headers/render.h"
#include "../../engine/headers/collisions.h" 

// Constants
const int BUBBLE_RADIUS = 20;
const int GRID_ROWS = 10;
const int GRID_COLS = 10; 
const int SHOOTER_POOL_SIZE = 100;

// Action IDs
const int BS_ACTION_LEFT = 10;
const int BS_ACTION_RIGHT = 11;
const int BS_ACTION_FIRE = 12;

class BubbleShooter {
public:
    BubbleShooter(SDL_Renderer* renderer, InputManager* input);
    ~BubbleShooter();

    void Init();
    void Update(float dt);
    void Render();
    bool IsGameOver() const { return gameOver; }
    void SpawnNextBubble();
    void DropGrid();
    void FindCluster(int r, int c, int targetColor, std::set<std::pair<int, int>>& visited);
    void DrawTrajectory();

private:
    SDL_Renderer* m_renderer;
    InputManager* m_input;

    // The Grid: nullptr = empty slot
    GameObject* m_grid[GRID_ROWS][GRID_COLS];

    // The Shooter
    GameObject* m_currentBubble; // The bubble waiting to be fired
    float m_shooterAngle;        // In degrees
    Vector m_shooterPos;

    // Active Projectile 
    GameObject* m_projectile; 
    Vector m_projectileVelocity;

    // Object Pool
    GameObjectPool* m_bubblePool;

    // Textures
    SDL_Texture* m_texRed;
    SDL_Texture* m_texBlue;
    SDL_Texture* m_texGreen;
    
    bool gameOver;

    // Helpers
    void SnapToGrid(GameObject* bubble);
    Vector GridToPixel(int row, int col);
    bool CheckCircleCollision(GameObject* a, GameObject* b); 
    void Fire();
    SDL_Texture* GetRandomTexture();
    SDL_Texture* CreateColoredTexture(int r, int g, int b);
};