#ifndef ENTITIES_H
#define ENTITIES_H

#include <mutex>
#include <atomic>
#include "struct.h"
#include "collisions.h"



class Entity
{
public:
    // Mutex Lock for Entity
    std::mutex entityMutex;

    // A simple constructor for our data-only entity
    Entity(Vector pos = {0,0}, Vector dim = {0,0}, Vector vel = {0,0}, bool phys = false);
    ~Entity();

    //Constructor (you may want a constructor which includes some arguments, like x,y position, texture file, etc.
	Entity();

	// Constructor with default velocity of (0,0)
	Entity(const Vector position, const Vector dimension, SDL_Texture* texture, bool physics);

	// Constructor with default velocity of (0,0) and auto-calculates dimensions
	Entity(const Vector position, SDL_Texture* texture, bool physics);

	// Constructor that auto-calculates dimensions
	Entity(const Vector position, SDL_Texture* texture, Vector velocity, bool physics);

    // Constructor with Full arguments
    Entity(const Vector pos, const Vector dim, SDL_Texture* tex, bool physics, const Vector vel);



    // Prevent accidental copying (pointers in collider)
    Entity(const Entity &) = delete;
    Entity &operator=(const Entity &) = delete;

    // Allow move semantics
    Entity(Entity &&) noexcept = default;
    Entity &operator=(Entity &&) noexcept = default;

    /*
	 * --------------------AI USE CITATION---------------------
	 * These special member functions were generated by GPT after I asked
	 * it to review the code in this file for best practices. I have decided to include
	 * them after reviewing the content and their intended purpose for memory/resource management.
	 * - hplenham
	*/
	Entity(const Entity&) = delete;
	Entity& operator=(const Entity&) = delete;
	Entity(Entity&&) noexcept = default;
	Entity& operator=(Entity&&) noexcept = default;

    // --- DATA MEMBERS ---
    // Entity's top left point
	Vector position;

	// Distance up and left to top left point
	Vector dimensions;
	// Velocity containing direction and magnitude
	Vector velocity;
	// Denotes if physics is applied to the entity - false by default.
	bool physicsApplied = false;
	// Entity Texture - null by default.
	SDL_Texture* texture = nullptr;
	// Entity's collider, defaults as null
	Collider* collider = nullptr;

    // Getters
    Vector getPosition();
    Vector getDimensions();
    Vector getVelocity();
    bool getPhysicsApplied();
    Collider getCollider();

    // Setters
    void setPosition(Vector newPosition);
    void setDimensions(Vector newDimensions);
    void setVelocity(Vector newVelocity);
    void setPhysicsApplied(bool newPhysicsApplied);
    void setCollider(Collider *newCollider);

    void makeCollider();
    void updatePosition();
    void updateCollider();
};

#endif // ENTITIES_H
