/*
	This is a header file that contains the function declarations for all functions in entities.cpp.
*/

#ifndef ENTITIES_H
#define ENTITIES_H

#include <SDL3/SDL_render.h>
#include "struct.h"

class Entity {
public:
	//Constructor (you may want a constructor which includes some arguments, like x,y position, texture file, etc.
	Entity();

	//Constructor (you may want a constructor which includes some arguments, like x,y position, texture file, etc.
	// Position, Dimensions, Texture, Physics?, Velocity
	Entity(const OrderedPair position, const OrderedPair dimension, SDL_Texture* texture, bool physics, const Velocity vel);

	//Destructor
	~Entity();

	/*
	 * --------------------AI USE CITATION---------------------
	 * These special member functions were generated by GPT after I asked
	 * it to review the code in this file for best practices. I have decided to include
	 * them after reviewing the content and their intended purpose for memory/resource management.
	 * - hplenham
	*/
	Entity(const Entity&) = delete;
	Entity& operator=(const Entity&) = delete;
	Entity(Entity&&) noexcept = default;
	Entity& operator=(Entity&&) noexcept = default;

	// Entity's bottom right point
	OrderedPair position;

	// Distance up and left to top left point
	OrderedPair dimensions;

	// Velocity containing direction and magnitude
	Velocity velocity;

	// Denotes if physics is applied to the entity - false by default.
	bool physicsApplied = false;

	// Entity Texture - null by default.
	SDL_Texture* texture = nullptr;

	// Use this or a similar function if you want to have an update function in each entity.
	//void update();

};

#endif //ENTITIES_H