/**
 * This file outlines the stuff needed for events. Some of the content in this file was generated by/edited with AI tools.
 * This citation is to abide by the syllabus requirement that "appropriate citations"
 * must be given when referring to external sources. More information is available upon request.
 */

#pragma once
#include <cstdint>
#include <string>
#include <functional>

// We are going to know each event by its ID.
using EventTypeID = std::uint32_t;

/**
 * Generic event struct - extendable
 */
struct Event
{
    // Timeline float value
    float timestamp;

    // No types or parameters
    Event(float ts) : timestamp(ts) {}
    virtual ~Event() = default;

    virtual EventTypeID GetEventTypeID() const = 0;
};

/**
 * Helper function to get EventTypeID from string
 */
inline EventTypeID GetEventTypeID(const std::string &name)
{
    return std::hash<std::string>{}(name);
}

/**
 * Collision event struct
 */
struct CollisionEvent : public Event
{
    static const EventTypeID STATIC_EVENT_TYPE_ID;

    virtual EventTypeID GetEventTypeID() const override
    {
        return STATIC_EVENT_TYPE_ID;
    }

    int objectA_ID;
    int objectB_ID;

    CollisionEvent(float ts, int a, int b)
        : Event(ts), objectA_ID(a), objectB_ID(b) {}
};

/**
 * Input event struct
 */
struct InputEvent : public Event
{
    static const EventTypeID STATIC_EVENT_TYPE_ID;
    virtual EventTypeID GetEventTypeID() const override
    {
        return STATIC_EVENT_TYPE_ID;
    }
    int action;
    int playerID;

    InputEvent(float ts, int act, int pID)
        : Event(ts), action(act), playerID(pID) {}
};

/**
 * Death event struct
 */
struct DeathEvent : public Event
{
    static const EventTypeID STATIC_EVENT_TYPE_ID;
    virtual EventTypeID GetEventTypeID() const override
    {
        return STATIC_EVENT_TYPE_ID;
    }
    int entityID;

    DeathEvent(float ts, int eID)
        : Event(ts), entityID(eID) {}
};

/**
 * Spawn event struct
 */
struct SpawnEvent : public Event
{
    static const EventTypeID STATIC_EVENT_TYPE_ID;
    virtual EventTypeID GetEventTypeID() const override
    {
        return STATIC_EVENT_TYPE_ID;
    }
    int entityID;
    float x, y;

    SpawnEvent(float ts, int eID, float posX, float posY)
        : Event(ts), entityID(eID), x(posX), y(posY) {}
};


/**
 * Start Recording event struct
 */
struct StartRecordingEvent : public Event
{
    static const EventTypeID STATIC_EVENT_TYPE_ID;
    virtual EventTypeID GetEventTypeID() const override
    {
        return STATIC_EVENT_TYPE_ID;
    }

    StartRecordingEvent(float ts, int eID)
        : Event(ts) {}
};

/**
 * Stop Recording event struct
 */
struct StopRecordingEvent : public Event
{
    static const EventTypeID STATIC_EVENT_TYPE_ID;
    virtual EventTypeID GetEventTypeID() const override
    {
        return STATIC_EVENT_TYPE_ID;
    }

    StopRecordingEvent(float ts, int eID)
        : Event(ts) {}
};

/**
 * Start Playback event struct
 */
struct StartPlaybackEvent : public Event
{
    static const EventTypeID STATIC_EVENT_TYPE_ID;
    virtual EventTypeID GetEventTypeID() const override
    {
        return STATIC_EVENT_TYPE_ID;
    }

    StartPlaybackEvent(float ts, int eID)
        : Event(ts) {}
};

/**
 * Stop Playback event struct
 */
struct StopPlaybackEvent : public Event
{
    static const EventTypeID STATIC_EVENT_TYPE_ID;
    virtual EventTypeID GetEventTypeID() const override
    {
        return STATIC_EVENT_TYPE_ID;
    }

    StopPlaybackEvent(float ts)
        : Event(ts) {}
};