/**
 * This file outlines the functions and members of the EventManager. Some of the content in this file was generated by/edited with AI tools.
 * This citation is to abide by the syllabus requirement that "appropriate citations"
 * must be given when referring to external sources. More information is available upon request.
 */
#pragma once
#include <functional>
#include <map>
#include <vector>
#include <memory>
#include <queue>
#include "../headers/Event.h"

using ListenerCallback = std::function<void(const Event &)>;

struct CompareEvent
{
    bool operator()(const std::shared_ptr<Event> &a, const std::shared_ptr<Event> &b)
    {
        return a->timestamp > b->timestamp;
    }
};

class EventManager
{
private:
    // A map where the key is the EventType, and the value is a list of
    // all functions (listeners) that care about that type.
    std::map<EventTypeID, std::vector<ListenerCallback>> listeners;
    std::priority_queue<
        std::shared_ptr<Event>,
        std::vector<std::shared_ptr<Event>>,
        CompareEvent>
        eventQueue;

public:
    void RegisterListener(EventTypeID type, ListenerCallback callback);
    void QueueEvent(std::shared_ptr<Event> event);
    void ProcessEvents(float currentTimestamp);
};