/**
 * This file outlines the stuff needed for events. Some of the content in this file was generated by/edited with AI tools.
 * This citation is to abide by the syllabus requirement that "appropriate citations"
 * must be given when referring to external sources. More information is available upon request.
 */

#pragma once

enum class EventType {
    Collision,
    Death,
    Spawn,
    Input
    //TODO add replay stuff
};

/**
 * Generic event struct - extendable
 */
struct Event {
    EventType type;
    // Timeline float value
    float timestamp;

    Event(EventType t, float ts) : type(t), timestamp(ts) {}
    virtual ~Event() = default;
};

/**
 * Collision event struct
 */
struct CollisionEvent : public Event {
    int objectA_ID;
    int objectB_ID;

    CollisionEvent(float ts, int a, int b) 
        : Event(EventType::Collision, ts), objectA_ID(a), objectB_ID(b) {}
};

/**
 * Input event struct
 */
struct InputEvent : public Event {
    int action;
    int playerID;

    InputEvent(float ts, int act, int pID) 
        : Event(EventType::Input, ts), action(act), playerID(pID) {}
};

/**
 * Death event struct
 */
struct DeathEvent : public Event {
    int entityID;

    DeathEvent(float ts, int eID) 
        : Event(EventType::Death, ts), entityID(eID) {}
};

/**
 * Spawn event struct
 */
struct SpawnEvent : public Event {
    int entityID;
    float x, y;

    SpawnEvent(float ts, int eID, float posX, float posY) 
        : Event(EventType::Spawn, ts), entityID(eID), x(posX), y(posY) {}
};